[package]
name = "pagemap_analyzer"
version = "0.1.0"
authors = ["Anton Danilkin <afdw@yandex.ru>"]
edition = "2018"

[dependencies]
nix = "0.18.0"
bitflags = "1.2.1"
byteorder = "1.3.4"
byte-unit = "4.0.9"
lazy_static = "1.4.0"
